# Generated by Django 5.1.6 on 2025-03-04 17:12

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("table", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            1: (
                                "wagtail_tinytableblock.blocks.TinyTableFieldBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("caption", 0), ("data", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
